### ISSUE TITLE
Witch's Magic Missile needs to be Replaced

### ISSUE THREAD

**Issue by Altoids1** [morrowwolf/Barony13#101]
While it's definitely a very important part of the witch's kit at the moment, I don't really think that much of our gameplay should be based on long stuns. So we're going to need a replacement.

Some options include:

Things already in the game somewhere:
- A smoke cloud

Things not in the game already:
- Perhaps some robust healing spell (balanced in similarity to Raynor's heal in HotS)
- A spell that shoots an arrow or non-stunning immovable rod through the Barony
- A spell to make goblins nearby be on her side

Stuff like that, I'unno.

**Comment by morrowwolf** [comment]
I like the idea of healing from taking health from cultists or skeletons.  I don't really like straight damage or just stunning so maybe something that can miss or is dodgable which I was hoping magic missile would work but not a big fan.

**Comment by ThatLing** [comment]
Life leech spell that leeches health from a target but you have to stay within X radius or it stops
