### ISSUE TITLE
You can't rotate wooden chairs

### ISSUE THREAD

**Issue by Altoids1** [morrowwolf/Barony13#128]

**Comment by ike709** [comment]
Yes you can. Alt click it, scrub.

**Comment by morrowwolf** [comment]
I alt-clicked the fuck out of it but I may be retarded.

**Comment by Parune** [comment]
To clarify, the chairs that are spawning in with the map can be rotated using alt click.  Chairs that have been picked up and placed down cannot be rotated using alt click.  I tried it during the test.
