### ISSUE TITLE
The cloak needs to be more compatible with weapon/tool in-hands

### ISSUE THREAD

**Issue by Parune** [morrowwolf/Barony13#131]
I've brought this up a couple times and it's kind of a minor thing, so I figured I'd make it an issue.  The cloak should respond to what's in the player's hands to avoid in-hand clipping.  So for example, when someone's holding something in their left hand, the sprite of the cloak changes to expose the person's left hand.  I've already made the sprites and they're on the drive, but the system just needs to be implemented (if it's possible).

**Comment by morrowwolf** [comment]
https://github.com/morrowwolf/Barony13/pull/175
