### ISSUE TITLE
Round end needs to add an exception to people staying inside their brains

### ISSUE THREAD

**Issue by morrowwolf** [morrowwolf/Barony13#29]

**Comment by Altoids1** [comment]
What does that mean

**Comment by morrowwolf** [comment]
So currently with the game mode it checks round end against the objectives of the witches.  The objective is decided as incomplete if a player is /mob/living and doesn't have a special role set in their mind.  People staying in their bodies counts as /mob/living hence not ending the round.  So there needs to be an added check of living status.
