### ISSUE TITLE
Charging occasionally causes a division-by-zero runtime

### ISSUE THREAD

**Issue by Altoids1** [morrowwolf/Barony13#30]
This seems to be a result caused by the game halting the `/mob/living/carbon/human/charge()` proc somewhere within this code block:
```dm
if(charge_cooldown == null || charge_cooldown <= world.time && get_dist(src,A) > 0)
		charge_cooldown = world.time + 50
		charging = TRUE
		if(get_dist(src,A) < CHARGE_RANGE)
			var/destination_x = (A.x - x) / sqrt((A.y - y)*(A.y - y) + (A.x - x)*(A.x - x)) * CHARGE_RANGE + x
			var/destination_y = (A.y - y) / sqrt((A.y - y)*(A.y - y) + (A.x - x)*(A.x - x)) * CHARGE_RANGE + y
			A = locate(round(destination_x, 1), round(destination_y, 1), z)
```
Because `get_dist(src,A) > 0` (as well as previously-used methods of doing this check like `A.x != x && A.y != y`) should mean that the division of their differences shouldn't cause any errors.

[The DM ref seems to suggest](http://www.byond.com/docs/ref/) that it would only ever halt procs like this if they had their `background` value set to 1, but apparently either I'm reading it wrong or that's just horseshit.

**Comment by morrowwolf** [comment]
I'll re-open this if this pops up again.
