### ISSUE TITLE
Allow for clicking to change direction of the shield block

### ISSUE THREAD

**Issue by morrowwolf** [morrowwolf/Barony13#35]
Currently you have to lower your shield to change the direction.  I'd like it to be that you can change the way you're blocking by clicking in that direction while the shield is up.

**Comment by Altoids1** [comment]
I actually kinda like the idea of keeping it the way it is.

Being forced to keep pointing a certain way adds a bit of skill requirement to the shield; it makes it so a knight must know when to block and when he has time to rotate to a better angle, making for what I think will probably end up being more exciting gameplay for both parties. I'd rather that the knight not be a character that is so stupidly perfect that he is rendered utterly impenetrable against peasants, but rather that he _can_ be penetrated in the circumstances that he is very stupid and the peasants are very skillful. 

To be honest, I prefer the sort of situation where the smarter & more experienced have better control over the game than the dumber ones, and that there is some way for the smart to "veto" the power of the dumb when it gets too bad. I think that will act as a sort of "invisible whitelist for being in control of the game" that will help make the game better & allow it to more coherently direct itself without admin intervention.

**Comment by morrowwolf** [comment]
So I can definitely see all of those points and I agree.  At the same time I do want to give a game that is fluid and feels good to play.

I also want the knight to be scary as hell to a peasant.  Barring extreme stupidity, a knight should be able to take a peasant out 1v1 no problem even if the peasant gets the jump on him.

**Comment by Altoids1** [comment]
Keep in mind that, as the game stands already, the knight still possesses much better armor and much better damage, meaning that even in surprise situations the knight is likely to be in the advantage. The knight will probably also be at a skill advantage most of the time, if we start doing hour requirements or whitelists for the role (which we probably should).

At least, that's my hunch. Balancing the knight v peasant fight is gonna take a lot of testing, not only right now but just like continually, for as long as this server exists.

**Comment by morrowwolf** [comment]
As to whitelisting and hour requirements the Baron is going to be whitelisted at the start and knights are going to have a 10 hour requirement that can/should be waived for players who've been around for the tests.

**Comment by Parune** [comment]
You could end up branching those two mechanics out to different pieces of equipment.  For instance, a buckler would allow you to turn but could have a breaking point, absorb a certain percentage of damage, or have something like an extended parry time.  Then, the bulkier shields would be for team combat, crowd control, and larger enemies.

I like the teamwork aspect of how the shield works right now, and I think the fluidity problem has more to do with the intuitiveness of it and the UI.  As long as people using the shield understand that you have to lower it and raise it again to change direction, it should play well.

**Comment by morrowwolf** [comment]
OK so how about this then at least?

https://github.com/morrowwolf/Barony13/pull/44

**Comment by DLCabbose** [comment]
Knight should be able to rotate their shield while blocking. Still feels to easy to get chumped when someone gets the jump on you. Shields should be a big deal.
