### ISSUE TITLE
FirehawkXO Staff Application

### ISSUE THREAD

**Issue by FirehawkXO** [morrowwolf/Barony13#58]
Steam Name(Current): Firehawk

Age: 17

Current Rank: Member

Why would you like to be promoted?: I know that I am able to be an upstanding staff member and appeal to the mass of the community. I feel that as the server picks up as we move forward in this project, I will be a helpful asset of the community as a staff member, but also as someone who actively plays the game. As one of the first players and alpha tester in this game I can bring a non-biased opinion on staff matters - as well as being there for damage control, if anything were to happen.

Why do you think we should promote you?: I love helping out new players by giving them tips on what to do when they first join and I believe that I am aware of all current rules and will always keep up to date with the rules if they ever were updated. 

Do you have any administrative experience:
Spirit of Gaming SWRP: Gamemaster
Spirit of Gaming DarkRP: Moderator
Nox Networks SWRP: Trial Gamemaster
Digital Delta Gaming DarkRP: Moderator
Burst Link Network: Administrator

Additional Details: I really love the server and the people that come along with it. I also thought there would be a place for referrals in the application format but there isn't, so I'll just put it below.

Referred by: Everyone

**Comment by DLCabbose** [comment]
Given the stage of development the server is currently undergoing, and your lack of experience with the specific game platform we're using, it's my judgement that a staff position would be blowing our load too quick. I'll keep you in mind, but I think you have plenty to offer as a member of the community.

We can explore this again at a later date, it's not impossible.
