### ISSUE TITLE
FirehawkXO Custom Job

### ISSUE THREAD

**Issue by FirehawkXO** [morrowwolf/Barony13#60]
Current name: FirehawkXO

Faction: Good Side

Job Name: The Scarlet King

Color: Color(196, 68, 209, 255)

Model: TBD

Model ID: TBD

Description: Beautiful Savior, King of creation, Son of God and Son of Man. Truly I'd love Thee, truly I'd serve Thee,  Light of my soul, my joy, my crown. Long Live the God King.

Did you pay for this?: Yes

**Comment by morrowwolf** [comment]
Go code it.
